spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student001?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtp
    username: nfwpp79gbl51km@163.com
    password: GVfWhaExL8qb9nBj
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.required: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  reasonable: true
  helper-dialect: mysql

#spring??????
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

